server:
  port: 8002

spring:
  profiles:
    active: dev
  application:
    name: jwt-auth-server

eureka:
  client:
    healthcheck:
       enabled: true
    serviceUrl:
       defaultZone: http://localhost:8001/eureka/
   # TODO wot?
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

# Stop Feign calls (via the underlying Ribbon technology) after 5-10 secs
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 10000

application:
  jwtSigningKey: fO6KnpqPw7l1zCLM0bDswTcRJ